@echo off
setlocal enabledelayedexpansion

echo ==================================================================================
echo                  EasyCloudPan - 一键配置脚本 (Setup)
echo ==================================================================================
echo.

:: 0. 工具准备 (Redis / FFmpeg)
echo [0/5] 检查并下载依赖工具 (Redis, FFmpeg)...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0download_tools.ps1"
if %errorlevel% neq 0 (
    echo [ERROR] 工具下载失败。您可以尝试手动下载 Redis 和 FFmpeg 到 tools 目录。
    echo 继续执行后续步骤? (按任一键继续，或关闭窗口)
    pause
) else (
    echo [OK] 依赖工具准备就绪。
)
echo.

:: 1. 环境检查
echo [1/5] 检查运行环境...

:: ... Java/Maven/Node check ...

:: MySQL Check (Simple port check or service check is hard in batch without tools, just guide)
echo Checking MySQL...
where mysql >nul 2>nul
if %errorlevel% neq 0 (
    echo [WARN] 未检测到 MySQL 命令行工具。
    echo        请确保本机已安装 MySQL 8.0+ 并启动服务。
    echo        如果没有安装，即将为您打开下载页面...
    timeout /t 3
    start https://dev.mysql.com/downloads/installer/
    echo.
    echo        安装完成后，请回来继续配置。
    pause
) else (
    echo [OK] 检测到 MySQL 客户端。
)

echo.
echo ----------------------------------------------------------------------------------
echo.

echo [2/5] 配置数据库与服务参数...

where java >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] 未检测到 Java，请确保已安装 JDK 1.8+ 并配置环境变量。
    pause
    exit /b 1
) else (
    echo [OK] Java 已安装。
)

where mvn >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] 未检测到 Maven，请确保已安装 Maven 并配置环境变量。
    pause
    exit /b 1
) else (
    echo [OK] Maven 已安装。
)

where node >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] 未检测到 Node.js，请确保已安装 Node.js 16+ 并配置环境变量。
    pause
    exit /b 1
) else (
    echo [OK] Node.js 已安装。
)

echo.
echo ----------------------------------------------------------------------------------
echo.

:: 2. 收集配置信息
echo [2/4] 配置数据库与服务参数...
echo.

set MYSQL_PWD=
set /p MYSQL_PWD="请输入 MySQL root 用户密码 (默认: 1234): "
if "!MYSQL_PWD!"=="" set MYSQL_PWD=1234

set REDIS_HOST=
set /p REDIS_HOST="请输入 Redis 地址 (默认: 127.0.0.1): "
if "!REDIS_HOST!"=="" set REDIS_HOST=127.0.0.1

set REDIS_PORT=
set /p REDIS_PORT="请输入 Redis 端口 (默认: 6379): "
if "!REDIS_PORT!"=="" set REDIS_PORT=6379

set FILE_PATH=
set /p FILE_PATH="请输入文件存储根目录 (默认: D:/easypan_data/): "
if "!FILE_PATH!"=="" set FILE_PATH=D:/easypan_data/

:: 转换为正斜杠并确保以 / 结尾
set FILE_PATH=!FILE_PATH:\=/!
if not "!FILE_PATH:~-1!"=="/" set FILE_PATH=!FILE_PATH!/

echo.
echo 正在生成配置文件...

:: 创建配置目录（如果不存在）
if not exist "backend\src\main\resources" mkdir "backend\src\main\resources"

:: 写入 application-local.properties
(
echo # Generated by setup.bat
echo server.port=7090
echo spring.datasource.url=jdbc:mysql://127.0.0.1:3306/easypan?serverTimezone=GMT%%2B8^&useUnicode=true^&characterEncoding=utf8^&autoReconnect=true^&allowMultiQueries=true^&useSSL=false
echo spring.datasource.username=root
echo spring.datasource.password=!MYSQL_PWD!
echo spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
echo.
echo spring.redis.host=!REDIS_HOST!
echo spring.redis.port=!REDIS_PORT!
echo spring.redis.database=0
echo.
echo # Dummy values for required placeholders
echo QQ_APP_ID=dummy_app_id
echo QQ_APP_KEY=dummy_app_key
echo SPRING_MAIL_PASSWORD=dummy_mail_password
echo.
echo project.folder=file:!FILE_PATH!
echo.
echo # logging
echo log.root.level=info
) > "backend\src\main\resources\application-local.properties"

echo [OK] 配置文件已生成: backend\src\main\resources\application-local.properties
echo.
echo ----------------------------------------------------------------------------------
echo.

:: 3. 安装依赖
echo [3/5] 安装前端依赖...
cd frontend
call npm install
if %errorlevel% neq 0 (
    echo [ERROR] 前端依赖安装失败，请检查网络或 Node.js 环境。
    cd ..
    pause
    exit /b 1
)
cd ..
echo [OK] 前端依赖安装完成。

echo.
echo ----------------------------------------------------------------------------------
echo.

:: 4. 创建存储目录
echo [4/5] 初始化存储目录...
if not exist "!FILE_PATH!" mkdir "!FILE_PATH!"
echo [OK] 存储目录已创建: !FILE_PATH!

:: 5. 数据库提示
echo.
echo ----------------------------------------------------------------------------------
echo [5/5] 数据库初始化提醒
echo.
echo 请确保您已经手动创建了数据库 'easypan' 并导入了 SQL 脚本。
echo 脚本路径: database/easypan.sql
echo.
echo 如果尚未导入，可以现在手动导入。
echo.

echo.
echo ==================================================================================
echo                  配置完成！现在可以运行 startup.bat 启动服务。
echo ==================================================================================
pause
