/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSearch: typeof import('./components/AdvancedSearch.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    AvatarUpload: typeof import('./components/AvatarUpload.vue')['default']
    BatchToolbar: typeof import('./components/BatchToolbar.vue')['default']
    ContextMenu: typeof import('./components/ContextMenu.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FolderSelect: typeof import('./components/FolderSelect.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    LoadingState: typeof import('./components/LoadingState.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NoData: typeof import('./components/NoData.vue')['default']
    Preview: typeof import('./components/preview/Preview.vue')['default']
    PreviewDoc: typeof import('./components/preview/PreviewDoc.vue')['default']
    PreviewDownload: typeof import('./components/preview/PreviewDownload.vue')['default']
    PreviewExcel: typeof import('./components/preview/PreviewExcel.vue')['default']
    PreviewImage: typeof import('./components/preview/PreviewImage.vue')['default']
    PreviewMusic: typeof import('./components/preview/PreviewMusic.vue')['default']
    PreviewPdf: typeof import('./components/preview/PreviewPdf.vue')['default']
    PreviewTxt: typeof import('./components/preview/PreviewTxt.vue')['default']
    PreviewVideo: typeof import('./components/preview/PreviewVideo.vue')['default']
    ProgressiveImage: typeof import('./components/ProgressiveImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table.vue')['default']
    VirtualTable: typeof import('./components/VirtualTable.vue')['default']
    Window: typeof import('./components/Window.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
